# Generated by Django 3.2.3 on 2021-05-20 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelsapp', '0002_auto_20210518_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=2)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='age',
            new_name='year_of_graduation',
        ),
        migrations.RemoveField(
            model_name='school',
            name='address',
        ),
        migrations.RemoveField(
            model_name='school',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_of_resumption',
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(default=5, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelsapp.faculty')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='Certificate_Type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='modelsapp.certificate_type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Department',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='modelsapp.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Grade',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='modelsapp.grade'),
            preserve_default=False,
        ),
    ]
